PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX n2mu: <http://cltl.nl/leolani/n2mu/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX leolaniFriends: <http://cltl.nl/leolani/friends/>


select DISTINCT ?person ?face_id ?name ?prefix
where {
    ?person rdf:type n2mu:person .
    ?person n2mu:faceID ?face_id .
    ?person rdfs:label ?name .
    
    
    FILTER(STRSTARTS(STR(?person), STR(leolaniFriends:)))
}